### ISSUE TITLE
Support for macOS 12.3.1

### ISSUE THREAD

**Issue by danil-z** [Boilertalk/Web3.swift#119] opened 2022-04-15 04:06 UTC
It seems that library fails to build for macOS 12.3.1.
Any plans to support current Apple platforms?

**Comment by koraykoska** [comment] 2022-04-15 07:56
What is the error?

**Comment by FrankSolleveld** [comment] 2022-04-25 11:35
Do you mean that your current operating system is macOS 12.3.1? I'm on that OS as well and have an Apple silicon chip. Web3.swift fails on `EthereumQuantityTag.swift` with the following error:
`'BigUInt' is ambiguous for type lookup in this context`

**Comment by Florian-S-A-W** [comment] 2022-10-12 17:29
I cannot reproduce this issue on macOS 12.6

**Comment by Florian-S-A-W** [comment] 2023-03-22 13:18
This issue seems to have been fixed in more recent macOS releases.

**Closed by Florian-S-A-W** 2023-03-22 13:18 UTC
